package types

import "go.vocdoni.io/dvote/types"

// BallotSignature is the signature generated by a voter to sign the ballot as
// a proof of the authorship of the vote.
type BallotSignature struct {
	R types.HexBytes `json:"r"`
	S types.HexBytes `json:"s"`
}
